### ISSUE TITLE
Uploaded documents not visible on the company portal

### ISSUE THREAD

**Issue by abhinav2342000** [ocs-iitd/issues#26]
When a document is uploaded by the student, it is visible on student portal, but not visible on the company portal.

**Comment by neelpy** [comment]
@divyam227227 is this resolved?

**Comment by divyam227227** [comment]
@neelpy I talked to @abhinav2342000 regarding this. The documents visibility is not to be given to the company but only to HoD. Closing this now.

**Comment by neelpy** [comment]
I think I changed that, @abhinav2342000  can you check again on the beta portal?
