### ISSUE TITLE
Interdisciplinary Branches

### ISSUE THREAD

**Issue by ayushchoubey03** [ocs-iitd/issues#41]
**Is your feature request related to a problem? Please describe.**
For interdisciplinary departments that usually get ignored by the companies during the program selection process, we can show them as a pop up in their sister branch.

**Describe the solution you'd like**
For example: when a company selects Energy Studies dept, a pop up recommendation should show up saying “people who select this also select MTech in Energy studies in interdisciplinary section”
Similarly, when a company selects MTech in Chemical engineering dept, a pop up should appear guiding them to select “MTech in Polymer Science and Technology” as well.

Similarly, we can discuss for the other 2 interdisciplinary programs if the feature can be included.  

** Screenshot**

![image](https://user-images.githubusercontent.com/29701783/87544773-a279c380-c6c4-11ea-90cc-f1db5383d28b.png)

**Comment by anilkumarsingh1911** [comment]
popup msg in parent department is not a good idea.

**Comment by anilkumarsingh1911** [comment]
resolved, no course in interdisciplinary area
